[EMA]
long = 1000
short = 50

[BULL]
rsi = 10
high = 80
low = 60
mod_high = 5
mod_low = -5

[BEAR]
rsi = 15
high = 50
low = 20
mod_high = 15
mod_low  = -5

[ADX]
adx = 3
high = 70
low = 50

[EXIT]
take_profit = 5
stop = 0.85
hodl = 0.01